### ISSUE TITLE
IndexError: too many indices for tensor of dimension 2

### ISSUE THREAD

**Issue by haze** [SivilTaram/Persona-Dialogue-Generation#15]
I've downloaded the weights and models into `tmp/psquare` and attempt to run `python interactive.py`
I'm met with this error:
```
Traceback (most recent call last):
  File "interactive.py", line 141, in <module>
    interactive(parser.parse_args(print_args=False), print_parser=parser)
  File "interactive.py", line 121, in interactive
    acts[1] = agents[1].act()
  File "/home/haze/Persona-Dialogue-Generation/agents/transmitter/transmitter.py", line 901, in act
    return self.batch_act([self.observation])[0]
  File "/home/haze/Persona-Dialogue-Generation/agents/transmitter/transmitter.py", line 875, in batch_act
    cand_inds, sampling_cands, is_training)
  File "/home/haze/Persona-Dialogue-Generation/agents/transmitter/transmitter.py", line 730, in predict
    valid_cands=valid_cands)
  File "/home/haze/Persona-Dialogue-Generation/agents/transmitter/gpt/model.py", line 124, in forward
    predictions, hidden_states = self.beam_search(batch_size, prior_context)
  File "/home/haze/Persona-Dialogue-Generation/agents/transmitter/gpt/model.py", line 416, in beam_search
    logits = outputs[:, -1, :]
IndexError: too many indices for tensor of dimension 2
```
Pytorch version: `1.6.0`
TensorboardX version: `2.1`
numpy version: `1.19.2`

**Comment by SivilTaram** [comment]
@haze Thank you for your interest on our paper. As stated in README, we recommend `pytorch >=1.0.1`, and could you please try it again under such an environment?

**Comment by haze** [comment]
@SivilTaram Sorry I had a typo. the version is actually `1.6.0` (edited in original comment)

**Comment by haze** [comment]
My deepest apologies, I've cleared my dependencies (within the `venv` doing `pip freeze` and uninstalling everything) and reattempted the installation (first, `torch==1.0.1`, then `tensorboardX`, then the custom dependencies). After this, the interactive script had worked. Thank you so much for the paper and research, it is much appreciated!
