### ISSUE TITLE
Run eval_f1.py: "TypeError: 'NoneType' object is not callable"

### ISSUE THREAD

**Issue by leyi-123** [SivilTaram/Persona-Dialogue-Generation#18]
When I run eval_f1.py after unzipping psquare_original.zip, an error appears: "TypeError: 'NoneType' object is not callable".

The specific question is as follow:

  Traceback (most recent call last):
  File "eval_f1.py", line 51, in <module>
    eval_f1(opt, print_parser=parser)
  File "eval_f1.py", line 35, in eval_f1
    report = eval_model(opt, print_parser)
  File "/home1/myname/Persona-Dialogue-Generation/parlai/scripts/eval_model.py", line 84, in eval_model
    world.parley()
  File "/home1/myname/Persona-Dialogue-Generation/parlai/core/worlds.py", line 663, in parley
    batch_act = self.batch_act(agent_idx, batch_observations[agent_idx])
  File "/home1/myname/Persona-Dialogue-Generation/parlai/core/worlds.py", line 636, in batch_act
    batch_actions = a.batch_act(batch_observation)
  File "/home1/myname/Persona-Dialogue-Generation/agents/transmitter/transmitter.py", line 857, in batch_act
    self.init_cuda_buffer(batchsize)
  File "/home1/myname/Persona-Dialogue-Generation/agents/transmitter/transmitter.py", line 842, in init_cuda_buffer
    sc = self.model(input_dummy, None, None, output_dummy, None)[1]
  File "/home1/myname/anaconda3/envs/p2bot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home1/myname/Persona-Dialogue-Generation/agents/transmitter/gpt/model.py", line 91, in forward
    lm_logits, hidden_states = self.transformer_module(input_seq, None, dis_seq)
TypeError: 'NoneType' object is not callable

Thank you for your help!

**Comment by SivilTaram** [comment]
@leyi-123 I cannot reproduce the errors. I think the installation of `transformers` library is not correct (we have customized some parts to support the auxiliary task).

Please see [here](https://github.com/SivilTaram/Persona-Dialogue-Generation#install-custom-dependencies) to see how to install the correct dependencies. Hope it helps you.

**Comment by leyi-123** [comment]
> 
> 
> @leyi-123 I cannot reproduce the errors. I think the installation of `transformers` library is not correct (we have customized some parts to support the auxiliary task).
> 
> Please see [here](https://github.com/SivilTaram/Persona-Dialogue-Generation#install-custom-dependencies) to see how to install the correct dependencies. Hope it helps you.

Thanks! I will try.
