### ISSUE TITLE
训练transmitter时报错，TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by 1973sir** [SivilTaram/Persona-Dialogue-Generation#25]
The following parameters will be optimized NORMALLY:
linear.weight
[ training... ]
[ Saving tensorboard logs here: ./tmp/transmitter/tensorboard ]
preinitializing pytorch cuda buffer
Traceback (most recent call last):
  File "train_transmitter.py", line 145, in <module>
    TrainLoop(opt).train()
  File "/disk1/lenny/share/PersonaDG/Persona-Dialogue-Generation/parlai/scripts/train_model.py", line 512, in train
    world.parley()
  File "/disk1/lenny/share/PersonaDG/Persona-Dialogue-Generation/parlai/core/worlds.py", line 663, in parley
    batch_act = self.batch_act(agent_idx, batch_observations[agent_idx])
  File "/disk1/lenny/share/PersonaDG/Persona-Dialogue-Generation/parlai/core/worlds.py", line 636, in batch_act
    batch_actions = a.batch_act(batch_observation)
  File "/disk1/lenny/share/PersonaDG/Persona-Dialogue-Generation/agents/transmitter/transmitter.py", line 857, in batch_act
    self.init_cuda_buffer(batchsize)
  File "/disk1/lenny/share/PersonaDG/Persona-Dialogue-Generation/agents/transmitter/transmitter.py", line 842, in init_cuda_buffer
    sc = self.model(input_dummy, None, None, output_dummy, None)[1]
  File "/home/lenny/anaconda3/envs/t18p20/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/disk1/lenny/share/PersonaDG/Persona-Dialogue-Generation/agents/transmitter/gpt/model.py", line 91, in forward
    lm_logits, hidden_states = self.transformer_module(input_seq, None, dis_seq)
TypeError: 'NoneType' object is not callable

**Comment by SivilTaram** [comment]
@1973sir  I cannot reproduce the errors. I think the installation of `transformers` library is not correct (we have customized some parts to support the auxiliary task).

Please see [here](https://github.com/SivilTaram/Persona-Dialogue-Generation#install-custom-dependencies) to see how to install the correct dependencies. Hope it helps you.

**Comment by 1973sir** [comment]
after create a new env with torch 1.01 and cuda 10.0 ,this error disapears.
