### ISSUE TITLE
Error when running interactive.py

### ISSUE THREAD

**Issue by baljit92** [SivilTaram/Persona-Dialogue-Generation#26]
Hi,

First of all, thank you very much for creating this repository. I believe this will be very useful to my current conversational project. 

However, I'm trying to run the `interactive.py` to test the current pre-trained model but I get the following error

```

[ Loading existing model params from <path>/Persona-Dialogue-Generation/data/models/convai2/kvmemnn/model ]
Dictionary: loading dictionary from <path>/Persona-Dialogue-Generation/data/models/convai2/kvmemnn/model.dict
[ num words =  19153 ]

Model name 'openai-gpt' was not found in model name list (openai-gpt). We assumed 'openai-gpt' was a path or url but couldn't find files https://s3.amazonaws.com/models.huggingface.co/bert/openai-gpt-vocab.json and https://s3.amazonaws.com/models.huggingface.co/bert/openai-gpt-merges.txt at this path or url.
Traceback (most recent call last):
  File "interactive.py", line 141, in <module>
    interactive(parser.parse_args(print_args=False), print_parser=parser)
  File "interactive.py", line 64, in interactive
    agent = create_agent(opt, requireModelExists=True)
  File "<path>/Persona-Dialogue-Generation/parlai/core/agents.py", line 547, in create_agent
    model = load_agent_module(opt)
  File "<path>/Persona-Dialogue-Generation/parlai/core/agents.py", line 424, in load_agent_module
    return model_class(new_opt)
  File "<path>/Persona-Dialogue-Generation/agents/transmitter/transmitter.py", line 324, in __init__
    self.dict = self.dictionary_class()(opt)
  File "<path>/Persona-Dialogue-Generation/agents/common/gpt_dictionary.py", line 70, in __init__
    self.start_idx = self.tokenizer.convert_tokens_to_ids([SpecialToken.start])[0]
AttributeError: 'NoneType' object has no attribute 'convert_tokens_to_ids
```

I have followed the instructions mentioned in [Custom Dependencies](https://github.com/SivilTaram/Persona-Dialogue-Generation#install-custom-dependencies) to setup the environment. 

Is there anything else I'm missing?

I'm using Python 3.7 on an Ubuntu environment.

**Comment by SivilTaram** [comment]
@baljit92  According to the message, I guess the install of `transformer` is not correct. Could you double-check that it is installed correctly?

**Comment by SivilTaram** [comment]
If there is any problem, pls feel free to re-open it.

**Comment by DanielBeck93** [comment]
@baljit92 , Did you solve this problem?
